[project]
name = "dbt-doris"
version = "0.3.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-doris>=0.3.4",
    "mysql-connector-python>=9.3.0",
]
